name: Build Dino Runner IA
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-pygbag:
    name: Dino Runner IA
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install pygbag
      run: |
        echo "Attempting to install pygbag"
        python -m pip install pygbag || { echo "pygbag installation failed"; exit 1; }
        echo "Successfully installed pygbag"
    - name: Build the game
      run: |
        echo "Attempting to build the game"
        python -m pygbag --build $GITHUB_WORKSPACE/main.py || { echo "Build failed"; exit 1; }
        echo "Successfully built the game and compiled to WebAssembly"
    - name: "Upload to GitHub pages branch gh-pages"
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: build/web
        token: ${{ secrets.GITHUB_TOKEN }}

